## kubectl installation
FROM docker:dind

RUN apk update && apk add curl python3

RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.15.0/bin/linux/amd64/kubectl
RUN chmod +x kubectl && mv ./kubectl /usr/local/bin/kubectl

## AWS cli installation
RUN curl -O https://bootstrap.pypa.io/get-pip.py
RUN python3 get-pip.py --user

RUN pip3 install awscli --upgrade --user
RUN mv ~/.local/bin/aws* /usr/local/bin/
